// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr_EvtiOOe0vVlMONHpjlWTlsiveme0Y4',
    appId: '1:131172754257:web:3123f6e831e08c15aea970',
    messagingSenderId: '131172754257',
    projectId: 'connectwork-584e6',
    authDomain: 'connectwork-584e6.firebaseapp.com',
    storageBucket: 'connectwork-584e6.firebasestorage.app',
    measurementId: 'G-8MQ4WS53BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3asqjPk1tRQ7l6-UJ9I6vQ-m5S7k5Sb8',
    appId: '1:131172754257:android:a29ac1d821cef2a8aea970',
    messagingSenderId: '131172754257',
    projectId: 'connectwork-584e6',
    storageBucket: 'connectwork-584e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA3UyX-FAImJQGqJLUJRXZBGMMT3BoZTo',
    appId: '1:131172754257:ios:c5e76ecd871056a8aea970',
    messagingSenderId: '131172754257',
    projectId: 'connectwork-584e6',
    storageBucket: 'connectwork-584e6.firebasestorage.app',
    iosBundleId: 'com.example.connectWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA3UyX-FAImJQGqJLUJRXZBGMMT3BoZTo',
    appId: '1:131172754257:ios:c5e76ecd871056a8aea970',
    messagingSenderId: '131172754257',
    projectId: 'connectwork-584e6',
    storageBucket: 'connectwork-584e6.firebasestorage.app',
    iosBundleId: 'com.example.connectWork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr_EvtiOOe0vVlMONHpjlWTlsiveme0Y4',
    appId: '1:131172754257:web:321023c95820316faea970',
    messagingSenderId: '131172754257',
    projectId: 'connectwork-584e6',
    authDomain: 'connectwork-584e6.firebaseapp.com',
    storageBucket: 'connectwork-584e6.firebasestorage.app',
    measurementId: 'G-2HSBS7XE7G',
  );
}
